version: '3.8'

volumes:
  postgres_data_dev: {}
  postgres_backup_dev: {}

services:
  postgres:
    container_name: postgres_server
    image: postgres:13.1-alpine
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - postgres_backup_dev:/backups
    env_file: .env
    networks:
      - network-backend

  django:
    container_name: django_server
    build: ./backend
    command: ["sh", "./start.sh"]
    volumes:
      - ./backend/:/usr/src/backend/
    ports:
      - 8000:8000
    depends_on:
      - postgres
    env_file: .env 
    networks:
      - network-backend
      - network-frontend

  node:
    container_name: node_server
    build: ./frontend
    command: ["sh", "./start.sh"]
    volumes: 
      - ./frontend/src:/usr/src/frontend/src
      - ./frontend/public:/usr/src/frontend/public
    depends_on:
      - django
    expose: 
      - 3000
    ports: 
      - 3000:3000
    env_file: .env 
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - network-frontend

networks:
  network-backend:
    name: platform_network-backend
    ipam:
        driver: default
        config:
          - subnet: 172.19.0.0/24

  network-frontend:
    name: platform_network-frontend